### ISSUE TITLE
Remove unused API

### ISSUE THREAD

**Issue by iSazonov** [PowerShell/PowerShell-Native#24]
We need remove unused APIs from the library after merging related PR in PowerShell repo:
- GetUserName https://github.com/PowerShell/PowerShell/pull/9531
- ~~IsSymLink~~ https://github.com/PowerShell/PowerShell/pull/9534
- GetFullyQualifiedName https://github.com/PowerShell/PowerShell/pull/9530

**Comment by TravisEz13** [comment]
These were removed in 7.0.0-preview.1.  So these API's cannot be removed until previous versions are out of support.

**Comment by adityapatwardhan** [comment]
Cannot remove IsSymLink because FollowSymLink uses it.
