### ISSUE TITLE
Microsoft.PowerShell.Native nupkg includes pdbs

### ISSUE THREAD

**Issue by SteveL-MSFT** [PowerShell/PowerShell-Native#26]
The published nupkg for Microsoft.PowerShell.Native includes the pdb for pwrshplugin.dll.  This causes pwsh.deps.json to declare a dependency on that symbol file.  This prevents building a single exe as that pdb isn't in the pkg but pwsh.deps.json prevents it from running.

This also means our regular pkg is being inflated by the inclusion of this pdb.

**Comment by SteveL-MSFT** [comment]
cc @adityapatwardhan

**Comment by tomas04** [comment]
Any progress on this issue?

**Comment by PSVortex** [comment]
I'm prepering NEt Core 3 + PowerShell 7 application and I can't release it unless it's single exe. Please fix this.
